name: 🚀 Feature Request
description: Propose a new feature for the project.
title: "[Feat]: "
labels: ["enhancement", "new feature"]

body:
  - type: textarea
    id: problem-statement
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of the problem you are trying to solve.
      placeholder: "Example: I'm always frustrated when I can't find a specific setting in the UI."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen. Be as specific as possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you have considered.
      placeholder: "Example: I've considered using the existing XYZ feature, but it doesn't fully solve the problem because..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.

  - type: markdown
    attributes:
      value: |
        ---
        Thanks for contributing! 🎉
