apiVersion: v1
kind: Service
metadata:
  name: {{ include "gatus.fullname" . }}
  labels:
    {{- include "gatus.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "gatus.selectorLabels" . | nindent 4 }}