# This workflow validates that all commits in a pull request are correctly signed.
# This ensures a verifiable chain of custody for all code contributions.

name: Enforce Signed Commits
permissions:
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  verify-signed-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history to ensure the GPG verification works correctly.
          fetch-depth: 0

      - name: Verify signed commits
        run: |
          # Get the commit range for the PR
          commit_range="${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
          commit_statuses=$(git log --pretty='%G? %h' $commit_range)

          echo "Verifying the following commits for a GPG signature:"
          echo "$commit_statuses"

          while read -r status commit_hash; do
            if [ "$status" != "G" ]; then
              echo "::error::Commit $commit_hash is not signed or has a bad signature. All commits must be signed."
              exit 1
            fi
          done <<< "$commit_statuses"

          echo "All commits in this pull request are correctly signed. ✅"
